######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 18 02:52:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoanCalcQtMainWindow.h LoanCalculator.h
SOURCES += LoanCalcQtMainWindow.cpp LoanCalculator.cpp LoanCalculatorMain.cpp
