#############################################################################
# Makefile for building: loanCalculatorCpp
# Generated by qmake (2.01a) (Qt 4.5.0) on: Wed Apr 18 02:52:11 2012
# Project:  loanCalculatorCpp.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile loanCalculatorCpp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I../cmdLineParser
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread -L../cmdLineParser -lCmdLineParser
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = LoanCalcQtMainWindow.cpp \
		LoanCalculator.cpp \
		LoanCalculatorMain.cpp moc_LoanCalcQtMainWindow.cpp
OBJECTS       = LoanCalcQtMainWindow.o \
		LoanCalculator.o \
		LoanCalculatorMain.o \
		moc_LoanCalcQtMainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		loanCalculatorCpp.pro
QMAKE_TARGET  = loanCalculator
DESTDIR       = 
TARGET        = loanCalculator

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

# Brady removed the Makefile target from the all target
#all: Makefile $(TARGET)
all: $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: loanCalculatorCpp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile loanCalculatorCpp.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile loanCalculatorCpp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/loanCalculatorCpp1.0.0 || $(MKDIR) .tmp/loanCalculatorCpp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/loanCalculatorCpp1.0.0/ && $(COPY_FILE) --parents LoanCalcQtMainWindow.h LoanCalculator.h .tmp/loanCalculatorCpp1.0.0/ && $(COPY_FILE) --parents LoanCalcQtMainWindow.cpp LoanCalculator.cpp LoanCalculatorMain.cpp .tmp/loanCalculatorCpp1.0.0/ && (cd `dirname .tmp/loanCalculatorCpp1.0.0` && $(TAR) loanCalculatorCpp1.0.0.tar loanCalculatorCpp1.0.0 && $(COMPRESS) loanCalculatorCpp1.0.0.tar) && $(MOVE) `dirname .tmp/loanCalculatorCpp1.0.0`/loanCalculatorCpp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/loanCalculatorCpp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_LoanCalcQtMainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_LoanCalcQtMainWindow.cpp
moc_LoanCalcQtMainWindow.cpp: LoanCalculator.h \
		LoanCalcQtMainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) LoanCalcQtMainWindow.h -o moc_LoanCalcQtMainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

LoanCalcQtMainWindow.o: LoanCalcQtMainWindow.cpp LoanCalculator.h \
		LoanCalcQtMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoanCalcQtMainWindow.o LoanCalcQtMainWindow.cpp

LoanCalculator.o: LoanCalculator.cpp LoanCalculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoanCalculator.o LoanCalculator.cpp

LoanCalculatorMain.o: LoanCalculatorMain.cpp LoanCalcQtMainWindow.h \
		LoanCalculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoanCalculatorMain.o LoanCalculatorMain.cpp

moc_LoanCalcQtMainWindow.o: moc_LoanCalcQtMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoanCalcQtMainWindow.o moc_LoanCalcQtMainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

